version: '3.6'
services:
  web:
    # DDev already sets this, add it here to debug Kernel tests.
    # May be fixed by https://github.com/drud/ddev/pull/3149
    environment:
      - PHP_IDE_CONFIG=serverName=$DDEV_HOSTNAME

    # Required for Drupal Test Traits. Will be fixed in ddev soon.
    # @see https://github.com/drud/ddev/issues/3158
    working_dir: /var/www/html
