version: '3.6'
services:
  chrome:
    container_name: ddev-${DDEV_SITENAME}-chrome
    image: previousnext/chrome-headless
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    external_links:
      - ddev-router:${DDEV_SITENAME}.${DDEV_TLD}
  web:
    links:
      - chrome:$DDEV_HOSTNAME
